BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX gettext(u'COOKIE_INFO_HEADER') XXXXX
        XXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'COOKIE_INFO_OK') XXXX
             gettext(u'COOKIE_INFO_PARA') 
        XXXX
    XXXXXX
XXXXXX